apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: devnation-s3-log
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: aws-s3-source
    properties:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
      region: ${AWS_REGION}
      bucketNameOrArn: ${AWS_S3_BUCKET_NAME}
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink